/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5ab87107-f213-4a01-9afc-8996900cfb93",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_kjkl01ZQm",
    "aws_user_pools_web_client_id": "58ei23kj3i91eia0muclgrsolo",
    "oauth": {}
};


export default awsmobile;
