# This action tests the environment whenever there's a PR open

name: Frontend CI

on:
    pull_request:
        paths: ['frontend/**.ts', 'frontend/**.tsx', 'frontend/**.js', 'frontend/**.jsx']

jobs:
    install:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      frontend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install Dependencies
              run: npm install

            - name: Install Frontend Dependencies
              run: npm --prefix frontend install

    lint:
        runs-on: ubuntu-18.04
        needs: install
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      frontend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Run linter
              run: npm run lint:frontend

    build:
        runs-on: ubuntu-18.04
        needs: install
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      frontend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Check that frontend compiles
              run: npm run build
