# This action tests the environment whenever there's a PR open

name: CI

on:
    pull_request:
        paths: ['**.ts', '**.tsx', '**.js', '**.jsx']

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            backend: ${{ steps.filter.outputs.backend }}
            frontend: ${{ steps.filter.outputs.frontend }}
        steps:
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      backend:
                        - 'backend/**'
                      frontend:
                        - 'frontend/**'

    install:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      frontend/node_modules
                      backend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install Dependencies
              run: npm install

    install-frontend:
        runs-on: ubuntu-18.04
        needs: changes
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      frontend/node_modules
                      backend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install Frontend Dependencies
              run: npm --prefix frontend install

    install-backend:
        runs-on: ubuntu-18.04
        needs: changes
        if: ${{ needs.changes.outputs.backend == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      frontend/node_modules
                      backend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install Backend Dependencies
              run: npm --prefix backend install

    lint:
        runs-on: ubuntu-18.04
        needs: install
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      frontend/node_modules
                      backend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Run linter
              run: npm run lint

    test-backend:
        runs-on: ubuntu-18.04
        needs: [install, changes]
        if: ${{ needs.changes.outputs.backend == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      frontend/node_modules
                      backend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Check that backend tests pass
              run: npm run test:backend

    build-frontend:
        runs-on: ubuntu-18.04
        needs: [install, changes]
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      frontend/node_modules
                      backend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Check that frontend compiles
              run: npm run build
